### ISSUE TITLE
Add explicit versioning - also to the latest container image

### ISSUE THREAD

**Issue by florath** [ContainerSSH/images#3]
## Please describe what you would like to see in ContainerSSH

It would be beneficial to have a dedicated tag for all released versions.

## Please describe the solution you'd like

In addition to the current "lastest" version on hub.docker.com, add a tag for each release.

## Please describe your use case

I just upgraded everything to 0.5 and it hopefully somehow works. Because there is no dedicated tag for the 0.5 version container image, with the next update of containerssh my environment might stop working.

I would like to have a tag like "0.5.0" for the release 0.5 to be able to use an image path like `containerssh/containerssh:0.5.0`

**Comment by tsipinakis** [comment]
There's already a per-version tag e.g. [v0.5.0](https://hub.docker.com/layers/containerssh/containerssh/v0.5.0/images/sha256-6172caeda46366eab7be42cb62df3080e2b61f76dbed66eda314b92b8b880822?context=explore) and a tag with the build date attached that won't be moved with rebuilds e.g.: [v0.5.0-20240107](https://hub.docker.com/layers/containerssh/containerssh/v0.5.0-20240107/images/sha256-6172caeda46366eab7be42cb62df3080e2b61f76dbed66eda314b92b8b880822?context=explore).

**Comment by florath** [comment]
Huups.
You are right. Scrolling helps...
Sorry.
